name: Test sapui5

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node dependencies
        run: npm install

      - name: Check Node and NPM versions
        run: |
          node --version
          npm --version
          which node
          which npm
          npx qunit --version

      - name: Run test-sapui5
        run: npm run test-sapui5
