name: Test sapui5

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: node --experimental-print-required-tla ./node_modules/.bin/qunit 'src/sapui5/**/tests/**/*.test.js'

      - name: Run tests
        run: qunit 'src/sapui5/**/tests/**/*.test.js'

      # - name: Run tests
      #   run: npx qunit 'src/sapui5/**/tests/**/*.test.js'
